# base image
FROM node:16-alpine

# setup folders and file locations
WORKDIR /app

COPY ./package.json .

# install nodejs dependencies, this looks for the package.json file
RUN npm install

COPY . .
RUN chown  node:node /app/node_modules

# default command, this looks for the index.js file
CMD ["npm", "run", "start"]
